# Generated by Django 5.0 on 2023-12-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_alter_interview_interview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='question_1',
            field=models.TextField(verbose_name='Ask about student profile'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='question_10',
            field=models.TextField(verbose_name='Summary of responses to any other question that the interview raised during the interview'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='question_11',
            field=models.TextField(verbose_name='Assess all the above with the personal statement included in the application form and give recommendations for the case'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='question_2',
            field=models.TextField(verbose_name="Ask student's family background and analyze financial circumstances"),
        ),
        migrations.AlterField(
            model_name='interview',
            name='question_3',
            field=models.TextField(verbose_name="Ask about student's career plans and future aspirations regarding studies or career"),
        ),
        migrations.AlterField(
            model_name='interview',
            name='question_4',
            field=models.TextField(verbose_name='How was education being financed till now?'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='question_5',
            field=models.TextField(verbose_name='How much financial support is required and what amount will be student contribution'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='question_6',
            field=models.TextField(verbose_name='For how long will the financial support be required?'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='question_7',
            field=models.TextField(verbose_name='Ask student if he/she was planning to manage his/her studies, especially if they have already started a program?'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='question_8',
            field=models.TextField(verbose_name='Why does the student feel he/she deserves this sponsorship?'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='question_9',
            field=models.TextField(verbose_name="What are the student's plans for self-sufficiency or increase in contribution in the future?"),
        ),
    ]
