# Generated by Django 5.0 on 2023-12-23 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0005_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_contact',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='SelectDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.donor')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.application')),
            ],
        ),
    ]
