# Generated by Django 5.0 on 2023-12-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0007_alter_selectdonor_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
