# Generated by Django 5.0 on 2023-12-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0008_alter_application_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
