# Generated by Django 5.0 on 2023-12-24 13:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0009_alter_application_total_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'verbose_name': 'Interview', 'verbose_name_plural': 'Interviews'},
        ),
        migrations.AddField(
            model_name='selectdonor',
            name='selection_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forecastentry',
            name='sponsorship_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
