# Generated by Django 5.0 on 2023-12-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0011_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Student'},
        ),
    ]
