# Generated by Django 5.0 on 2023-12-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0012_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name_plural': '1:Application'},
        ),
        migrations.AlterModelOptions(
            name='degree',
            options={'verbose_name_plural': 'Degrees'},
        ),
        migrations.AlterModelOptions(
            name='forecastentry',
            options={'verbose_name_plural': '4:Fore_cast_Entry'},
        ),
        migrations.AlterModelOptions(
            name='interview',
            options={'verbose_name': 'Interview', 'verbose_name_plural': '3:Interviews'},
        ),
        migrations.AlterModelOptions(
            name='selectdonor',
            options={'verbose_name_plural': '5:Select_Donor'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='verification',
            options={'verbose_name': 'Verification', 'verbose_name_plural': '2:Verifications'},
        ),
    ]
