# Generated by Django 5.0 on 2023-12-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0013_alter_application_options_alter_degree_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='institution_name',
            new_name='institution_interested_in',
        ),
        migrations.RemoveField(
            model_name='application',
            name='level_of_education',
        ),
        migrations.RemoveField(
            model_name='application',
            name='verification_submitted',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='cnic_or_b_form',
        ),
        migrations.AddField(
            model_name='application',
            name='cnic_or_b_form',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='current_level_of_education',
            field=models.CharField(choices=[('Primary School', 'Primary School'), ('Secondary School', 'Secondary School'), ('Intermediate', 'Intermediate'), ('O levels ', 'O levels '), ('A levels ', 'A levels '), ('Metrics', 'Metrics'), ('FSC', 'FSC'), ('Bachelors Degree', 'Bachelors Degree'), ('Masters', 'Masters'), ('Diploma / Certificate', 'Diploma / Certificate'), ('Other', 'Other')], default='Primary School', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='program_interested_in',
            field=models.CharField(choices=[('Primary School', 'Primary School'), ('Secondary School', 'Secondary School'), ('Intermediate', 'Intermediate'), ('O levels ', 'O levels '), ('A levels ', 'A levels '), ('Metrics', 'Metrics'), ('FSC', 'FSC'), ('Bachelors Degree', 'Bachelors Degree'), ('Masters', 'Masters'), ('Diploma / Certificate', 'Diploma / Certificate'), ('Other', 'Other')], max_length=255),
        ),
    ]
