# Generated by Django 5.0 on 2023-12-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0014_rename_institution_name_application_institution_interested_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='accommodation_amount',
            new_name='account_expenses',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='living_amount',
            new_name='admission_fee_of_the_program',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='total_cost_of_program',
            new_name='food_and_necessities_expenses',
        ),
        migrations.AddField(
            model_name='application',
            name='living_expenses',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='total_fee_of_the_program',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
