# Generated by Django 5.0 on 2023-12-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0016_interview_accepted_verification_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='recommendations',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='summary_responses',
        ),
        migrations.AlterField(
            model_name='interview',
            name='Accepted',
            field=models.CharField(choices=[('-', '-'), ('yes', 'yes'), ('no', 'no')], default='-', max_length=15),
        ),
    ]
