# Generated by Django 5.0 on 2023-12-30 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0018_application_description_of_household'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectionSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField()),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sponsor_name', models.CharField(max_length=255)),
                ('sponsorship_commitment', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fee_due_date', models.DateField()),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.student')),
            ],
        ),
        migrations.DeleteModel(
            name='ForecastEntry',
        ),
    ]
