# Generated by Django 5.0 on 2023-12-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0019_projectionsheet_delete_forecastentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='student',
            name='student_name',
            field=models.CharField(default='jawad', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectionsheet',
            name='other_fee',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='projectionsheet',
            name='sponsorship_commitment',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='projectionsheet',
            name='total_cost',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='projectionsheet',
            name='tuition_fee',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
