# Generated by Django 5.0 on 2023-12-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0020_rename_name_student_username_student_student_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='donor_cnic',
            field=models.CharField(default='123', max_length=13),
            preserve_default=False,
        ),
    ]
