# Generated by Django 5.0 on 2023-12-31 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0021_donor_donor_cnic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('program_type', models.CharField(choices=[('months', 'months'), ('semesters', 'semesters')], max_length=50)),
                ('duration_in_months', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='program_interested_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.program'),
        ),
    ]
