# Generated by Django 4.2.6 on 2024-02-25 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0026_documents_results_remove_application_account_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interview_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 2, 25, 6, 11, 38, 957418, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
